# Generated by Django 4.2.4 on 2024-05-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redseauser',
            name='is_sks_admin',
            field=models.BooleanField(default=False),
        ),
    ]
