# Generated by Django 4.2.4 on 2024-05-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_clubs', '0002_redseauser_is_sks_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
