# Generated by Django 4.2.4 on 2024-05-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_clubs', '0004_alter_event_event_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='club',
            table='Clubs',
        ),
    ]
