# Generated by Django 4.2.4 on 2024-05-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_clubs', '0005_alter_club_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='club',
            table=None,
        ),
    ]
